name: A workflow for a commit in project repositorie
on: push
jobs:
  build:
    name: Push action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Luca"
